# Generated by Django 2.0.1 on 2018-05-07 18:30

from django.db import migrations, models
import shortener.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20180129_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainurl',
            name='url',
            field=models.CharField(max_length=220, validators=[shortener.validators.validate_url, shortener.validators.validate_dot_com]),
        ),
    ]
